#!/bin/bash
systemctl enable lightdm
rm -rf /usr/share/music/bensound-sunny.mp3
rm -rf /usr/bin/dde-wm-chooser
rm -rf /usr/share/applications/gxde-control-center.desktop
rm -rf /lib/dde-dock
rm -rf /lib/gxde-dock/libtrash.so
rm -rf /lib/gxde-dock/libnotify.so
cp /usr/bin/gxde-shutdown-live /usr/bin/dde-shutdown